theme: minima
title: Borujen | بروجن
author: People of Borujen | مردم بروجن
description: A Page Dedicated to the City of Borujen | صفحه ای که به شهرستان بروجن می پردازد
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
